### ISSUE TITLE
big bug!!

### ISSUE THREAD

**Issue by michaelcanudas** [Redninja106/AdventOfCode#1]
so i noticed a bug when running code so basically when i run code opened in visual studio 2022 it is the preview version by the way so when i run the code i notice there is a bug if i run but then turn off my computer i think this should be accounted for in the code just incase the user turns off their computer and stuff because what would happen if a user was to do so they would be very sad when they realize what just occur and then they would quit code forever so for the good of humanity and for the good of humanity i think that we should totally fix that thanks

**Comment by Redninja106** [comment]
closing as this is a duplicate
